language: python

python:
  - "3.5"
  - "3.5-dev"

install:
    - pip install -r requirements.txt
    - pip install coveralls

script: make test

after_success:
      coveralls

branches:
  only:
  - master

notifications:
  email: false
